config/routes.rb
Rails.application.routes.draw do
  resources :dams
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # root 'pages#home'
  root 'dams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dam.rb
class Dam < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/dams_controller.rb
class DamsController < ApplicationController
  before_action :set_dam, only: [:show, :edit, :update, :destroy]

  # GET /dams
  # GET /dams.json
  def index
    @dams = Dam.all
  end

  # GET /dams/1
  # GET /dams/1.json
  def show
  end

  # GET /dams/new
  def new
    @dam = Dam.new
  end

  # GET /dams/1/edit
  def edit
  end

  # POST /dams
  # POST /dams.json
  def create
    @dam = Dam.new(dam_params)

    respond_to do |format|
      if @dam.save
        format.html { redirect_to @dam, notice: 'Dam was successfully created.' }
        format.json { render :show, status: :created, location: @dam }
      else
        format.html { render :new }
        format.json { render json: @dam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dams/1
  # PATCH/PUT /dams/1.json
  def update
    respond_to do |format|
      if @dam.update(dam_params)
        format.html { redirect_to @dam, notice: 'Dam was successfully updated.' }
        format.json { render :show, status: :ok, location: @dam }
      else
        format.html { render :edit }
        format.json { render json: @dam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dams/1
  # DELETE /dams/1.json
  def destroy
    @dam.destroy
    respond_to do |format|
      format.html { redirect_to dams_url, notice: 'Dam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dam
      @dam = Dam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dam_params
      params.require(:dam).permit(:name, :region, :size, :dam_created)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  skip_before_action :authenticate_user!, :only => [:index]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dams_helper.rb
module DamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dams/_form.html.erb
<%= form_with(model: dam, local: true) do |form| %>
  <% if dam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dam.errors.count, "error") %> prohibited this dam from being saved:</h2>

      <ul>
        <% dam.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dam_code %>
    <%= form.text_field :dam_code %>
  </div>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :dam_created %>
    <%= form.datetime_select :dam_created, {:start_year => 1900, :end_year => Date.current.year} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dams/edit.html.erb
<h1>Editing Dam</h1>

<%= render 'form', dam: @dam %>

<%= link_to 'Show', @dam %> |
<%= link_to 'Back', dams_path %>

app/views/dams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dams</h1>

<table>
  <thead>
    <tr>
      <th>Dam Code</th>
      <th>Name</th>
      <th>Region</th>
      <th>Size</th>
      <th>Dam created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dams.each do |dam| %>
      <tr>
        <td><%= dam.dam_code %></td>
        <td><%= dam.name %></td>
        <td><%= dam.region %></td>
        <td><%= dam.size %></td>
        <td><%= dam.dam_created %></td>
        <td><%= link_to 'Show', dam %></td>
        <td><%= link_to 'Edit', edit_dam_path(dam) %></td>
        <td><%= link_to 'Destroy', dam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dam', new_dam_path %>

app/views/dams/new.html.erb
<h1>New Dam</h1>

<%= render 'form', dam: @dam %>

<%= link_to 'Back', dams_path %>

app/views/dams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dam.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @dam.region %>
</p>

<p>
  <strong>Size:</strong>
  <%= @dam.size %>
</p>

<p>
  <strong>Dam created:</strong>
  <%= @dam.dam_created %>
</p>

<%= link_to 'Edit', edit_dam_path(@dam) %> |
<%= link_to 'Back', dams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sertifikasi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>